clip function for primitive types added
Kotlin/multik pull request #96
Opened 2022-02-11 09:05 UTC by cagriyildirimR

There was a small typo in README

Clip operation is missing for Complex types because they are not Comparable. I am also not sure how to implement it. Should we compare them based on their real part only?

If Comparable interface were added to complex arrays then I think this function should work without any refactoring.

If I am missing anything please let me know.

2022-02-14 15:41 UTC, devcrocod commented
Hi, Cargi!
Thanks for the pull request!

Complex types aren't comparable in the mathematical sense. We deliberately did not come up with our own comparison methods to avoid UB. At the same time, in some methods, you can pass your own comparator, so you can explicitly determine how to compare complex numbers.

2022-02-14 15:45 UTC, devcrocod commented
Thanks for the fix in the readme.
With the new release, we will completely rewrite it, since the library will change a lot.

2022-02-14 15:48 UTC, devcrocod commented
@zaleslaw 
I think it will be interesting for you to take a look at this pr

2022-02-14 16:14 UTC, devcrocod requested changes

2022-02-14 16:14 UTC, devcrocod commented on multik-api/src/commonMain/kotlin/org/jetbrains/kotlinx/multik/ndarray/operations/Transformation.kt
> +internal fun <T: Comparable<T>, D: Dimension> MultiArray<T, D>.clip(min: T, max: T): NDArray<T,D> {
can be more specific type T:
``` ...): NDArray<T, D> where T : Number, T: Comparable<T>```

2022-02-14 16:14 UTC, devcrocod commented on multik-api/src/commonMain/kotlin/org/jetbrains/kotlinx/multik/ndarray/operations/Transformation.kt
> +    return NDArray(data = clippedData, shape = shape, dim = dim)
Don't forget that primitives arrays are passed by reference. So shape is passed here by reference, so changing the shape in the first ndarray will change the shape in the resulting ndarray from the clip function.

2022-02-15 13:14 UTC, zaleslaw commented
yeah @devcrocod it looks like a missed chain!

2022-02-21 16:58 UTC, devcrocod approved these changes

2022-02-21 16:58 UTC, merged